spring.application.name=digital

# 1. Conexão com o Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:comandadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar a tela do banco no seu navegador (Para vermos as tabelas depois!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Mostrar os comandos SQL no terminal (Ótimo para estudar como o Spring trabalha por baixo dos panos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Criar e atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update